name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Task 5
      id: task-5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Task 5
        setup-command: npm install
        command: npm test -- task5.test.js
        timeout: 10
        max-score: 30
    - name: Task 2
      id: task-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Task 2
        setup-command: npm install
        command: npm test -- task2.test.js
        timeout: 10
        max-score: 15
    - name: Task 3
      id: task-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Task 3
        setup-command: npm install
        command: npm test -- task3.test.js
        timeout: 10
        max-score: 20
    - name: Task 4
      id: task-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Task 4
        setup-command: npm install
        command: npm test -- task4.test.js
        timeout: 10
        max-score: 20
    - name: Task 1
      id: task-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Task 1
        setup-command: npm install
        command: npm test -- task1.test.js
        timeout: 10
        max-score: 15
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TASK-5_RESULTS: "${{steps.task-5.outputs.result}}"
        TASK-2_RESULTS: "${{steps.task-2.outputs.result}}"
        TASK-3_RESULTS: "${{steps.task-3.outputs.result}}"
        TASK-4_RESULTS: "${{steps.task-4.outputs.result}}"
        TASK-1_RESULTS: "${{steps.task-1.outputs.result}}"
      with:
        runners: task-5,task-2,task-3,task-4,task-1
